var namespace_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio =
[
    [ "AudioTagDetectedEventArgs", "class_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio_1_1_audio_tag_detected_event_args.html", "class_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio_1_1_audio_tag_detected_event_args" ],
    [ "AudioTagDetector", "class_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio_1_1_audio_tag_detector.html", "class_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio_1_1_audio_tag_detector" ],
    [ "DetectorStoppedEventArgs", "class_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio_1_1_detector_stopped_event_args.html", "class_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio_1_1_detector_stopped_event_args" ],
    [ "VolumeChangedEventArgs", "class_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio_1_1_volume_changed_event_args.html", "class_powa_tag_1_1_windows_phone_1_1_sdk_1_1_triggers_1_1_audio_1_1_volume_changed_event_args" ]
];