var annotated =
[
    [ "com", null, [
      [ "powatag", null, [
        [ "android", null, [
          [ "sdk", null, [
            [ "triggers", null, [
              [ "audio", null, [
                [ "AudioTagDetector", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector" ],
                [ "AudioTagDetectorListener", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector_listener.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector_listener" ]
              ] ],
              [ "barcode", null, [
                [ "Barcode", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode" ],
                [ "BarcodeFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_format.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_format" ],
                [ "BarcodeTagDetectorView", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view" ],
                [ "BarcodeTagDetectorViewListener", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view_listener.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view_listener" ],
                [ "Image", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image" ],
                [ "ImageFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image_format.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image_format" ]
              ] ],
              [ "touch2buy", null, [
                [ "AppLink", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link" ],
                [ "AppLinkTagDetector", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link_tag_detector.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link_tag_detector" ]
              ] ]
            ] ],
            [ "ui", null, [
              [ "ProductVariantPicker", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_product_variant_picker.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_product_variant_picker" ]
            ] ],
            [ "AcceptedPaymentInstrument", "classcom_1_1powatag_1_1android_1_1sdk_1_1_accepted_payment_instrument.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_accepted_payment_instrument" ],
            [ "AccessToken", "classcom_1_1powatag_1_1android_1_1sdk_1_1_access_token.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_access_token" ],
            [ "Act", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act" ],
            [ "ActDataKey", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_key.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_key" ],
            [ "ActDataType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_type" ],
            [ "ActManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_manager" ],
            [ "ActTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction" ],
            [ "ActTransactionDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction_details" ],
            [ "ActWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_workflow" ],
            [ "Address", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address" ],
            [ "AddressDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_details" ],
            [ "AddressDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_details_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_details_validator" ],
            [ "AddressLineValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_line_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_line_validator" ],
            [ "AliasValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_alias_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_alias_validator" ],
            [ "Basket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket" ],
            [ "BasketItem", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_item.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_item" ],
            [ "Baskets", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets" ],
            [ "BasketsManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets_manager" ],
            [ "Campaign", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign" ],
            [ "CampaignManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_manager" ],
            [ "CampaignWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_workflow" ],
            [ "CardHolderNameValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_card_holder_name_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_card_holder_name_validator" ],
            [ "CardNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_card_number_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_card_number_validator" ],
            [ "Cost", "classcom_1_1powatag_1_1android_1_1sdk_1_1_cost.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_cost" ],
            [ "Country", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country" ],
            [ "CreditCardIssuer", "classcom_1_1powatag_1_1android_1_1sdk_1_1_credit_card_issuer.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_credit_card_issuer" ],
            [ "CreditCardValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_credit_card_validator.html", null ],
            [ "CustomDataKey", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_key.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_key" ],
            [ "CustomDataType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_type" ],
            [ "CustomDataValue", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_value.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_value" ],
            [ "CvvValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_cvv_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_cvv_validator" ],
            [ "DonationAmountValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_amount_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_amount_validator" ],
            [ "DonationInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice" ],
            [ "DonationInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice_details" ],
            [ "EmailSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_email_sign_in_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_email_sign_in_details" ],
            [ "EmailValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_email_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_email_validator" ],
            [ "EncryptedCvv", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv" ],
            [ "EncryptedCvvStorage", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv_storage.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv_storage" ],
            [ "ExpiryDateValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_expiry_date_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_expiry_date_validator" ],
            [ "FormatValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_format_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_format_validator" ],
            [ "Inventory", "classcom_1_1powatag_1_1android_1_1sdk_1_1_inventory.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_inventory" ],
            [ "Invoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice" ],
            [ "InvoiceBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_basket" ],
            [ "InvoiceType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_type" ],
            [ "IssueNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_issue_number_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_issue_number_validator" ],
            [ "LoginManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_login_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_login_manager" ],
            [ "LuhnValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_luhn_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_luhn_validator" ],
            [ "MaxDecimalValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_max_decimal_value_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_max_decimal_value_validator" ],
            [ "MaxIntValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_max_int_value_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_max_int_value_validator" ],
            [ "MaxLengthValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_max_length_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_max_length_validator" ],
            [ "Merchant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant" ],
            [ "MinDecimalValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_min_decimal_value_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_min_decimal_value_validator" ],
            [ "MinIntValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_min_int_value_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_min_int_value_validator" ],
            [ "MinLengthValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_min_length_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_min_length_validator" ],
            [ "MobileNumberSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_mobile_number_sign_in_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_mobile_number_sign_in_details" ],
            [ "MobileNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_mobile_number_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_mobile_number_validator" ],
            [ "ModelValidator", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_model_validator.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_model_validator" ],
            [ "NameValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_name_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_name_validator" ],
            [ "NotEmptyValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_not_empty_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_not_empty_validator" ],
            [ "NotNullValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_not_null_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_not_null_validator" ],
            [ "Payment", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment" ],
            [ "PaymentDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_details" ],
            [ "PaymentInstrument", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument" ],
            [ "PaymentInstrumentDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details" ],
            [ "PaymentInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice" ],
            [ "PaymentInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice_details" ],
            [ "PaymentManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_manager" ],
            [ "PaymentMethodDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_method_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_method_details" ],
            [ "PaymentMethodDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_method_details_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_method_details_validator" ],
            [ "PaymentType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_payment_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_payment_type" ],
            [ "PersistentBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_persistent_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_persistent_basket" ],
            [ "PosBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket" ],
            [ "PosBasketItem", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket_item.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket_item" ],
            [ "PosManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_manager" ],
            [ "PosProductVariant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_product_variant.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_product_variant" ],
            [ "PostcodeValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_postcode_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_postcode_validator" ],
            [ "PowaTagAuthorizationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_authorization_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_authorization_exception" ],
            [ "PowaTagCallback", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_callback.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_callback" ],
            [ "PowaTagCancellationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_cancellation_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_cancellation_exception" ],
            [ "PowaTagClient", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_client.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_client" ],
            [ "PowaTagEndpoint", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_endpoint.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_endpoint" ],
            [ "PowaTagException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_exception" ],
            [ "PowaTagExecutor", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_executor.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_executor" ],
            [ "PowaTagHttpException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_http_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_http_exception" ],
            [ "PowaTagInvalidApiKeyException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_api_key_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_api_key_exception" ],
            [ "PowaTagInvalidDonationAmountException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_donation_amount_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_donation_amount_exception" ],
            [ "PowaTagInvalidTagFormatException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_tag_format_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_tag_format_exception" ],
            [ "PowaTagInvalidWorkflowTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_workflow_type_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_workflow_type_exception" ],
            [ "PowaTagKit", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_kit.html", null ],
            [ "PowaTagKitNotInitializedException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_kit_not_initialized_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_kit_not_initialized_exception" ],
            [ "PowaTagMissingRequiredActDataValuesException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_missing_required_act_data_values_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_missing_required_act_data_values_exception" ],
            [ "PowaTagNetworkException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_exception" ],
            [ "PowaTagNetworkTimeoutException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_timeout_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_timeout_exception" ],
            [ "PowaTagNoInternetConnectionException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_no_internet_connection_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_no_internet_connection_exception" ],
            [ "PowaTagNotFoundException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_not_found_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_not_found_exception" ],
            [ "PowaTagOutOfStockException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_out_of_stock_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_out_of_stock_exception" ],
            [ "PowaTagQrCode", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_qr_code.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_qr_code" ],
            [ "PowaTagSerializationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_serialization_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_serialization_exception" ],
            [ "PowaTagServiceException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_exception" ],
            [ "PowaTagServiceValidationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_validation_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_validation_exception" ],
            [ "PowaTagUndefinedPropertySerializationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_undefined_property_serialization_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_undefined_property_serialization_exception" ],
            [ "PowaTagUnsupportedActDataTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_act_data_type_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_act_data_type_exception" ],
            [ "PowaTagUnsupportedCustomDataTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_custom_data_type_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_custom_data_type_exception" ],
            [ "PowaTagUnsupportedFeatureException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_feature_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_feature_exception" ],
            [ "PowaTagUnsupportedWorkflowTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_workflow_type_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_workflow_type_exception" ],
            [ "PowaTagValidationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_validation_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_validation_exception" ],
            [ "Product", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product" ],
            [ "ProductAttribute", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_attribute.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_attribute" ],
            [ "ProductCondition", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_product_condition.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_product_condition" ],
            [ "ProductImage", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_image.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_image" ],
            [ "ProductOption", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option" ],
            [ "ProductOptionChoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_choice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_choice" ],
            [ "ProductOptionState", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_state.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_state" ],
            [ "ProductVariant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant" ],
            [ "ProductVariantFilter", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_filter.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_filter" ],
            [ "ProductWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_workflow" ],
            [ "Profile", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile" ],
            [ "ProfileDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_details" ],
            [ "ProfileDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_details_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_details_validator" ],
            [ "ProfileIdSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_id_sign_in_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_id_sign_in_details" ],
            [ "ProfileManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_manager" ],
            [ "ProfileService", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_service.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_service" ],
            [ "ProfileValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_validator.html", null ],
            [ "PropertyValidator", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_property_validator.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_property_validator" ],
            [ "ServiceError", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_error.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_error" ],
            [ "ShippingOption", "classcom_1_1powatag_1_1android_1_1sdk_1_1_shipping_option.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_shipping_option" ],
            [ "SignUpDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_sign_up_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_sign_up_details" ],
            [ "Tag", "classcom_1_1powatag_1_1android_1_1sdk_1_1_tag.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_tag" ],
            [ "TagFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_tag_format.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_tag_format" ],
            [ "TemporaryBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket" ],
            [ "TemporaryBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket_workflow" ],
            [ "TitleValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_title_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_title_validator" ],
            [ "UKAddressValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_u_k_address_validator.html", null ],
            [ "UkPostcodeValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_uk_postcode_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_uk_postcode_validator" ],
            [ "ValidationError", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_validation_error.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_validation_error" ],
            [ "ValidationFailure", "classcom_1_1powatag_1_1android_1_1sdk_1_1_validation_failure.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_validation_failure" ],
            [ "Validator", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_validator.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_validator" ],
            [ "ValidFromDateValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1_valid_from_date_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_valid_from_date_validator" ],
            [ "Workflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow" ],
            [ "WorkflowManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_manager" ],
            [ "WorkflowType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_type" ],
            [ "YearMonth", "classcom_1_1powatag_1_1android_1_1sdk_1_1_year_month.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_year_month" ]
          ] ]
        ] ]
      ] ]
    ] ]
];