var hierarchy =
[
    [ "com.powatag.android.sdk.ActDataKeyJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_key_json.html", null ],
    [ "com.powatag.android.sdk.ActDataType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_type.html", null ],
    [ "com.powatag.android.sdk.profile.ActivationStatus", "enumcom_1_1powatag_1_1android_1_1sdk_1_1profile_1_1_activation_status.html", null ],
    [ "com.powatag.android.sdk.ActJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_json.html", null ],
    [ "com.powatag.android.sdk.ActManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_manager.html", null ],
    [ "com.powatag.android.sdk.triggers.touch2buy.AppLinkTagDetector", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link_tag_detector.html", null ],
    [ "com.powatag.android.sdk.triggers.audio.AudioTagDetector", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector.html", null ],
    [ "com.powatag.android.sdk.triggers.audio.AudioTagDetectorListener", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector_listener.html", null ],
    [ "com.powatag.android.sdk.triggers.barcode.BarcodeFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_format.html", null ],
    [ "com.powatag.android.sdk.triggers.barcode.BarcodeTagDetectorViewListener", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view_listener.html", null ],
    [ "com.powatag.android.sdk.Base64Utils", "classcom_1_1powatag_1_1android_1_1sdk_1_1_base64_utils.html", null ],
    [ "com.powatag.android.sdk.payment.BasketInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1payment_1_1_basket_invoice.html", null ],
    [ "com.powatag.android.sdk.Baskets", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets.html", null ],
    [ "com.powatag.android.sdk.BasketsManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets_manager.html", null ],
    [ "com.powatag.android.sdk.BlockingPowaTagExecutor", "classcom_1_1powatag_1_1android_1_1sdk_1_1_blocking_powa_tag_executor.html", null ],
    [ "com.powatag.android.sdk.HttpClient.Callback", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_http_client_1_1_callback.html", null ],
    [ "com.powatag.android.sdk.CallbackFactoryModule", "classcom_1_1powatag_1_1android_1_1sdk_1_1_callback_factory_module.html", null ],
    [ "com.powatag.android.sdk.CampaignJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_json.html", null ],
    [ "com.powatag.android.sdk.CampaignManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_manager.html", null ],
    [ "com.powatag.android.sdk.validators.CardHolderNameValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_card_holder_name_validator.html", null ],
    [ "com.powatag.android.sdk.CardJson", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_card_json.html", [
      [ "com.powatag.android.sdk.PaymentCardJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_card_json.html", null ],
      [ "com.powatag.android.sdk.UnionPayCardJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_union_pay_card_json.html", null ]
    ] ],
    [ "com.powatag.android.sdk.ContextInjector", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_context_injector.html", null ],
    [ "com.powatag.android.sdk.CountryJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country_json.html", null ],
    [ "com.powatag.android.sdk.CouponManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_coupon_manager.html", null ],
    [ "com.powatag.android.sdk.coupon.CouponType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_coupon_type.html", null ],
    [ "com.powatag.android.sdk.validators.CreditCardValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_credit_card_validator.html", null ],
    [ "com.powatag.android.sdk.CustomDataKeyJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_key_json.html", null ],
    [ "com.powatag.android.sdk.CustomDataType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_type.html", null ],
    [ "com.powatag.android.sdk.validators.CvvValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_cvv_validator.html", null ],
    [ "com.powatag.android.sdk.validators.DonationAmountValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_donation_amount_validator.html", null ],
    [ "com.powatag.android.sdk.validators.EmailValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_email_validator.html", null ],
    [ "com.powatag.android.sdk.EncryptedCvvStorage", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv_storage.html", null ],
    [ "com.powatag.android.sdk.EncryptionUtils", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encryption_utils.html", null ],
    [ "com.powatag.android.sdk.validators.ExpiryDateValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_expiry_date_validator.html", null ],
    [ "com.powatag.android.sdk.GeoRestrictionJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_restriction_json.html", null ],
    [ "com.powatag.android.sdk.HttpRequest", "classcom_1_1powatag_1_1android_1_1sdk_1_1_http_request.html", null ],
    [ "com.powatag.android.sdk.HttpResponse", "classcom_1_1powatag_1_1android_1_1sdk_1_1_http_response.html", null ],
    [ "com.powatag.android.sdk.triggers.barcode.ImageFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image_format.html", null ],
    [ "com.powatag.android.sdk.InventoryJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_inventory_json.html", null ],
    [ "com.powatag.android.sdk.InvoiceBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_basket.html", null ],
    [ "com.powatag.android.sdk.InvoiceJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_json.html", [
      [ "com.powatag.android.sdk.PaymentInvoiceJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice_json.html", null ]
    ] ],
    [ "com.powatag.android.sdk.InvoiceType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_type.html", null ],
    [ "com.powatag.android.sdk.validators.IssueNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_issue_number_validator.html", null ],
    [ "com.powatag.android.sdk.LocalizedEntityJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_localized_entity_json.html", null ],
    [ "com.powatag.android.sdk.LoginManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_login_manager.html", null ],
    [ "com.powatag.android.sdk.ManagerComponent", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_manager_component.html", null ],
    [ "com.powatag.android.sdk.ManagerContextModule", "classcom_1_1powatag_1_1android_1_1sdk_1_1_manager_context_module.html", null ],
    [ "com.powatag.android.sdk.ManagerFactory", "classcom_1_1powatag_1_1android_1_1sdk_1_1_manager_factory.html", null ],
    [ "com.powatag.android.sdk.MerchantManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant_manager.html", null ],
    [ "com.powatag.android.sdk.validators.ModelValidator< T >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_model_validator.html", null ],
    [ "com.powatag.android.sdk.validators.ModelValidator< AddressDetails >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_model_validator.html", [
      [ "com.powatag.android.sdk.validators.AddressDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_address_details_validator.html", null ]
    ] ],
    [ "com.powatag.android.sdk.validators.ModelValidator< PaymentMethodDetails >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_model_validator.html", [
      [ "com.powatag.android.sdk.validators.PaymentMethodDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_payment_method_details_validator.html", null ]
    ] ],
    [ "com.powatag.android.sdk.validators.ModelValidator< ProfileDetails >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_model_validator.html", [
      [ "com.powatag.android.sdk.validators.ProfileDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_profile_details_validator.html", null ]
    ] ],
    [ "com.powatag.android.sdk.MoneyJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_money_json.html", null ],
    [ "com.powatag.android.sdk.triggers.nfc.NfcTagDetector", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1nfc_1_1_nfc_tag_detector.html", null ],
    [ "com.powatag.android.sdk.Page", "classcom_1_1powatag_1_1android_1_1sdk_1_1_page.html", null ],
    [ "Parcelable", null, [
      [ "com.powatag.android.sdk.AcceptedPaymentInstrument", "classcom_1_1powatag_1_1android_1_1sdk_1_1_accepted_payment_instrument.html", null ],
      [ "com.powatag.android.sdk.AccessToken", "classcom_1_1powatag_1_1android_1_1sdk_1_1_access_token.html", null ],
      [ "com.powatag.android.sdk.Act", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act.html", null ],
      [ "com.powatag.android.sdk.ActDataKey", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_key.html", null ],
      [ "com.powatag.android.sdk.ActTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction.html", null ],
      [ "com.powatag.android.sdk.ActTransactionDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction_details.html", null ],
      [ "com.powatag.android.sdk.Address", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address.html", null ],
      [ "com.powatag.android.sdk.AddressDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_details.html", null ],
      [ "com.powatag.android.sdk.BasketCost", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_cost.html", null ],
      [ "com.powatag.android.sdk.BasketItem", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_item.html", null ],
      [ "com.powatag.android.sdk.Campaign", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign.html", null ],
      [ "com.powatag.android.sdk.CampaignWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_workflow.html", null ],
      [ "com.powatag.android.sdk.CardNumberRange", "classcom_1_1powatag_1_1android_1_1sdk_1_1_card_number_range.html", null ],
      [ "com.powatag.android.sdk.Catalog", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog.html", null ],
      [ "com.powatag.android.sdk.Category", "classcom_1_1powatag_1_1android_1_1sdk_1_1_category.html", null ],
      [ "com.powatag.android.sdk.Cost", "classcom_1_1powatag_1_1android_1_1sdk_1_1_cost.html", null ],
      [ "com.powatag.android.sdk.Country", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country.html", null ],
      [ "com.powatag.android.sdk.coupon.Coupon", "classcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_coupon.html", null ],
      [ "com.powatag.android.sdk.coupon.Discount", "classcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_discount.html", null ],
      [ "com.powatag.android.sdk.CustomDataKey", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_key.html", null ],
      [ "com.powatag.android.sdk.CustomDataValue", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_value.html", null ],
      [ "com.powatag.android.sdk.DonationInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice.html", null ],
      [ "com.powatag.android.sdk.DonationInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice_details.html", null ],
      [ "com.powatag.android.sdk.EmailSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_email_sign_in_details.html", null ],
      [ "com.powatag.android.sdk.FulfillmentOption", "classcom_1_1powatag_1_1android_1_1sdk_1_1_fulfillment_option.html", null ],
      [ "com.powatag.android.sdk.GeoLocation", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_location.html", null ],
      [ "com.powatag.android.sdk.GeoRestriction", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_restriction.html", null ],
      [ "com.powatag.android.sdk.Inventory", "classcom_1_1powatag_1_1android_1_1sdk_1_1_inventory.html", null ],
      [ "com.powatag.android.sdk.Invoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice.html", [
        [ "com.powatag.android.sdk.DonationInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice.html", null ],
        [ "com.powatag.android.sdk.PaymentInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice.html", null ],
        [ "com.powatag.android.sdk.PosInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_invoice.html", null ]
      ] ],
      [ "com.powatag.android.sdk.Merchant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant.html", null ],
      [ "com.powatag.android.sdk.MerchantLocation", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant_location.html", null ],
      [ "com.powatag.android.sdk.MobileNumberSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_mobile_number_sign_in_details.html", null ],
      [ "com.powatag.android.sdk.Payment", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment.html", null ],
      [ "com.powatag.android.sdk.PaymentDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_details.html", null ],
      [ "com.powatag.android.sdk.PaymentInstrumentDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details.html", null ],
      [ "com.powatag.android.sdk.PaymentInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice_details.html", null ],
      [ "com.powatag.android.sdk.PaymentMethodDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_method_details.html", null ],
      [ "com.powatag.android.sdk.PowaTagQrCode", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_qr_code.html", null ],
      [ "com.powatag.android.sdk.Product", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product.html", null ],
      [ "com.powatag.android.sdk.ProductAttribute", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_attribute.html", null ],
      [ "com.powatag.android.sdk.ProductImage", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_image.html", null ],
      [ "com.powatag.android.sdk.ProductOption", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option.html", null ],
      [ "com.powatag.android.sdk.ProductOptionChoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_choice.html", null ],
      [ "com.powatag.android.sdk.ProductOptionState", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_state.html", null ],
      [ "com.powatag.android.sdk.ProductVariant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant.html", null ],
      [ "com.powatag.android.sdk.ProductVariantFilter", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_filter.html", null ],
      [ "com.powatag.android.sdk.ProductWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_workflow.html", null ],
      [ "com.powatag.android.sdk.Profile", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile.html", null ],
      [ "com.powatag.android.sdk.ProfileDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_details.html", null ],
      [ "com.powatag.android.sdk.ProfileIdSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_id_sign_in_details.html", null ],
      [ "com.powatag.android.sdk.ShippingPrice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_shipping_price.html", null ],
      [ "com.powatag.android.sdk.SignUpDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_sign_up_details.html", null ],
      [ "com.powatag.android.sdk.Tag", "classcom_1_1powatag_1_1android_1_1sdk_1_1_tag.html", null ],
      [ "com.powatag.android.sdk.TemporaryBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket_workflow.html", null ],
      [ "com.powatag.android.sdk.triggers.barcode.Barcode", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode.html", null ],
      [ "com.powatag.android.sdk.triggers.barcode.Image", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image.html", null ],
      [ "com.powatag.android.sdk.triggers.touch2buy.AppLink", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link.html", null ],
      [ "com.powatag.android.sdk.ui.coupon.CouponState", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1coupon_1_1_coupon_state.html", null ],
      [ "com.powatag.android.sdk.YearMonth", "classcom_1_1powatag_1_1android_1_1sdk_1_1_year_month.html", null ]
    ] ],
    [ "com.powatag.android.sdk.PasscodeEncryptionService", "classcom_1_1powatag_1_1android_1_1sdk_1_1_passcode_encryption_service.html", null ],
    [ "com.powatag.android.sdk.PaymentInstrumentDetailsRequestJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details_request_json.html", null ],
    [ "com.powatag.android.sdk.PaymentInstrumentDetailsResponseJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details_response_json.html", null ],
    [ "com.powatag.android.sdk.PaymentManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_manager.html", null ],
    [ "com.powatag.android.sdk.PaymentService", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_service.html", null ],
    [ "com.powatag.android.sdk.PaymentType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_payment_type.html", null ],
    [ "com.powatag.android.sdk.ui.Picker< T >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_picker.html", [
      [ "com.powatag.android.sdk.ui.coupon.CouponPicker", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1coupon_1_1_coupon_picker.html", null ]
    ] ],
    [ "com.powatag.android.sdk.ui.Picker< Coupon >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_picker.html", null ],
    [ "com.powatag.android.sdk.PosBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket.html", null ],
    [ "com.powatag.android.sdk.PosInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_invoice_details.html", null ],
    [ "com.powatag.android.sdk.PosManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_manager.html", null ],
    [ "com.powatag.android.sdk.PowaTagCallback< TResult >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_callback.html", null ],
    [ "com.powatag.android.sdk.PowaTagCallback< com.powatag.android.sdk.PowaTagQrCode >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_callback.html", null ],
    [ "com.powatag.android.sdk.PowaTagCallback< QrCodeJson >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_callback.html", [
      [ "com.powatag.android.sdk.GenerateQrCodeWorkflowCallback", "classcom_1_1powatag_1_1android_1_1sdk_1_1_generate_qr_code_workflow_callback.html", null ]
    ] ],
    [ "com.powatag.android.sdk.PowaTagCallback< Response< TResponseBody > >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_callback.html", null ],
    [ "com.powatag.android.sdk.PowaTagClient", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_client.html", null ],
    [ "com.powatag.android.sdk.PowaTagExecutor< TResult >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_executor.html", null ],
    [ "com.powatag.android.sdk.PowaTagKit", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_kit.html", null ],
    [ "com.powatag.android.sdk.ProductCategoryJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_category_json.html", null ],
    [ "com.powatag.android.sdk.ProductCondition", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_product_condition.html", null ],
    [ "com.powatag.android.sdk.product.ProductManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1product_1_1_product_manager.html", null ],
    [ "com.powatag.android.sdk.ProductOptionJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_json.html", null ],
    [ "com.powatag.android.sdk.ProductVariantJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_json.html", null ],
    [ "com.powatag.android.sdk.ui.ProductVariantPicker", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_product_variant_picker.html", null ],
    [ "com.powatag.android.sdk.ProductVariantRequestJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_request_json.html", null ],
    [ "com.powatag.android.sdk.ProfileCacheManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_cache_manager.html", null ],
    [ "com.powatag.android.sdk.profile.ProfileDefaultErrorHandler", "classcom_1_1powatag_1_1android_1_1sdk_1_1profile_1_1_profile_default_error_handler.html", null ],
    [ "com.powatag.android.sdk.ProfileManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_manager.html", null ],
    [ "com.powatag.android.sdk.ProfileService", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_service.html", null ],
    [ "com.powatag.android.sdk.validators.ProfileValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_profile_validator.html", null ],
    [ "com.powatag.android.sdk.merchant.PromotionStatus", "enumcom_1_1powatag_1_1android_1_1sdk_1_1merchant_1_1_promotion_status.html", null ],
    [ "com.powatag.android.sdk.validators.PropertyValidator< T >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_property_validator.html", null ],
    [ "com.powatag.android.sdk.validators.PropertyValidator< Double >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_property_validator.html", null ],
    [ "com.powatag.android.sdk.validators.PropertyValidator< Integer >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_property_validator.html", null ],
    [ "com.powatag.android.sdk.validators.PropertyValidator< String >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_property_validator.html", [
      [ "com.powatag.android.sdk.validators.CardNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_card_number_validator.html", null ],
      [ "com.powatag.android.sdk.validators.MobileNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_mobile_number_validator.html", null ],
      [ "com.powatag.android.sdk.validators.PasscodeValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_passcode_validator.html", null ]
    ] ],
    [ "com.powatag.android.sdk.validators.PropertyValidator< YearMonth >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_property_validator.html", null ],
    [ "RuntimeException", null, [
      [ "com.powatag.android.sdk.PowaTagException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_exception.html", [
        [ "com.powatag.android.sdk.io.StorageException", "classcom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storage_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagAuthorizationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_authorization_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagCancellationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_cancellation_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagHttpException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_http_exception.html", [
          [ "com.powatag.android.sdk.PowaTagServiceException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_exception.html", [
            [ "com.powatag.android.sdk.PowaTagConflictException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_conflict_exception.html", null ],
            [ "com.powatag.android.sdk.PowaTagNotFoundException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_not_found_exception.html", null ],
            [ "com.powatag.android.sdk.PowaTagOutOfStockException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_out_of_stock_exception.html", null ],
            [ "com.powatag.android.sdk.PowaTagServiceValidationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_validation_exception.html", null ]
          ] ]
        ] ],
        [ "com.powatag.android.sdk.PowaTagInvalidApiKeyException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_api_key_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagInvalidDonationAmountException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_donation_amount_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagInvalidTagFormatException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_tag_format_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagInvalidWorkflowTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_workflow_type_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagKitNotInitializedException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_kit_not_initialized_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagNetworkException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_exception.html", [
          [ "com.powatag.android.sdk.PowaTagNetworkTimeoutException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_timeout_exception.html", null ],
          [ "com.powatag.android.sdk.PowaTagNoInternetConnectionException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_no_internet_connection_exception.html", null ]
        ] ],
        [ "com.powatag.android.sdk.PowaTagSerializationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_serialization_exception.html", [
          [ "com.powatag.android.sdk.PowaTagUndefinedPropertySerializationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_undefined_property_serialization_exception.html", null ]
        ] ],
        [ "com.powatag.android.sdk.PowaTagUnsupportedActDataTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_act_data_type_exception.html", null ],
        [ "com.powatag.android.sdk.PowaTagUnsupportedFeatureException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_feature_exception.html", [
          [ "com.powatag.android.sdk.PowaTagUnsupportedCustomDataTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_custom_data_type_exception.html", null ],
          [ "com.powatag.android.sdk.PowaTagUnsupportedWorkflowTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_workflow_type_exception.html", null ]
        ] ],
        [ "com.powatag.android.sdk.PowaTagValidationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_validation_exception.html", [
          [ "com.powatag.android.sdk.PowaTagMissingRequiredActDataValuesException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_missing_required_act_data_values_exception.html", null ]
        ] ]
      ] ]
    ] ],
    [ "com.powatag.android.sdk.ui.Selectable< T >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_selectable.html", [
      [ "com.powatag.android.sdk.ui.coupon.CouponState", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1coupon_1_1_coupon_state.html", null ]
    ] ],
    [ "com.powatag.android.sdk.ui.Selectable< Coupon >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_selectable.html", null ],
    [ "com.powatag.android.sdk.ServiceError", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_error.html", null ],
    [ "com.powatag.android.sdk.ServiceErrorCodes", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_error_codes.html", null ],
    [ "com.powatag.android.sdk.ServiceModule", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_module.html", null ],
    [ "com.powatag.android.sdk.io.StorageService", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storage_service.html", [
      [ "com.powatag.android.sdk.io.LocalStorageService", "classcom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_local_storage_service.html", null ]
    ] ],
    [ "com.powatag.android.sdk.TagFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_tag_format.html", null ],
    [ "com.powatag.android.sdk.TemporaryBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket.html", null ],
    [ "com.powatag.android.sdk.Title", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_title.html", null ],
    [ "com.powatag.android.sdk.validators.TitleValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_title_validator.html", null ],
    [ "com.powatag.android.sdk.transaction.Transaction", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction.html", [
      [ "com.powatag.android.sdk.transaction.ActTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_act_transaction.html", null ],
      [ "com.powatag.android.sdk.transaction.BasketTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_basket_transaction.html", null ],
      [ "com.powatag.android.sdk.transaction.DonationTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_donation_transaction.html", null ],
      [ "com.powatag.android.sdk.transaction.PosTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_pos_transaction.html", null ]
    ] ],
    [ "com.powatag.android.sdk.transaction.TransactionManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction_manager.html", null ],
    [ "com.powatag.android.sdk.transaction.TransactionsContainer", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transactions_container.html", null ],
    [ "com.powatag.android.sdk.transaction.TransactionType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction_type.html", null ],
    [ "com.powatag.android.sdk.validators.UKAddressValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_u_k_address_validator.html", null ],
    [ "com.powatag.android.sdk.utils.UrlDecoder", "classcom_1_1powatag_1_1android_1_1sdk_1_1utils_1_1_url_decoder.html", null ],
    [ "com.powatag.android.sdk.validators.ValidationError", "enumcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validation_error.html", null ],
    [ "com.powatag.android.sdk.validators.ValidationFailure", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validation_failure.html", null ],
    [ "com.powatag.android.sdk.validators.Validator< T >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validator.html", null ],
    [ "com.powatag.android.sdk.validators.Validator< Double >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validator.html", [
      [ "com.powatag.android.sdk.validators.MaxDecimalValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_decimal_value_validator.html", null ],
      [ "com.powatag.android.sdk.validators.MinDecimalValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_decimal_value_validator.html", null ]
    ] ],
    [ "com.powatag.android.sdk.validators.Validator< Integer >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validator.html", [
      [ "com.powatag.android.sdk.validators.MaxIntValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_int_value_validator.html", null ],
      [ "com.powatag.android.sdk.validators.MinIntValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_int_value_validator.html", null ]
    ] ],
    [ "com.powatag.android.sdk.validators.Validator< Object >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validator.html", [
      [ "com.powatag.android.sdk.validators.NotNullValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_not_null_validator.html", null ]
    ] ],
    [ "com.powatag.android.sdk.validators.Validator< String >", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validator.html", [
      [ "com.powatag.android.sdk.validators.FormatValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_format_validator.html", null ],
      [ "com.powatag.android.sdk.validators.LuhnValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_luhn_validator.html", null ],
      [ "com.powatag.android.sdk.validators.MaxLengthValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_length_validator.html", null ],
      [ "com.powatag.android.sdk.validators.MinLengthValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_length_validator.html", null ],
      [ "com.powatag.android.sdk.validators.NotEmptyValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_not_empty_validator.html", null ]
    ] ],
    [ "com.powatag.android.sdk.validators.ValidFromDateValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_valid_from_date_validator.html", null ],
    [ "com.powatag.android.sdk.WeightUnit", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_weight_unit.html", null ],
    [ "com.powatag.android.sdk.WorkflowManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_manager.html", null ],
    [ "com.powatag.android.sdk.WorkflowType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_type.html", null ],
    [ "Parcelable", null, [
      [ "com.powatag.android.sdk.ActWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_workflow.html", null ],
      [ "com.powatag.android.sdk.CatalogWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog_workflow.html", null ],
      [ "com.powatag.android.sdk.CreditCardIssuer", "classcom_1_1powatag_1_1android_1_1sdk_1_1_credit_card_issuer.html", null ],
      [ "com.powatag.android.sdk.PaymentInstrument", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument.html", null ],
      [ "com.powatag.android.sdk.PosBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket_workflow.html", null ],
      [ "com.powatag.android.sdk.Workflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow.html", [
        [ "com.powatag.android.sdk.ActWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_workflow.html", null ],
        [ "com.powatag.android.sdk.CampaignWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_workflow.html", null ],
        [ "com.powatag.android.sdk.CatalogWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog_workflow.html", null ],
        [ "com.powatag.android.sdk.PosBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket_workflow.html", null ],
        [ "com.powatag.android.sdk.ProductWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_workflow.html", null ],
        [ "com.powatag.android.sdk.TemporaryBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket_workflow.html", null ]
      ] ]
    ] ],
    [ "Serializable", null, [
      [ "com.powatag.android.sdk.AcceptedPaymentInstrument", "classcom_1_1powatag_1_1android_1_1sdk_1_1_accepted_payment_instrument.html", null ],
      [ "com.powatag.android.sdk.AccessToken", "classcom_1_1powatag_1_1android_1_1sdk_1_1_access_token.html", null ],
      [ "com.powatag.android.sdk.Act", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act.html", null ],
      [ "com.powatag.android.sdk.ActDataKey", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_key.html", null ],
      [ "com.powatag.android.sdk.ActTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction.html", null ],
      [ "com.powatag.android.sdk.ActTransactionDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction_details.html", null ],
      [ "com.powatag.android.sdk.ActWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_workflow.html", null ],
      [ "com.powatag.android.sdk.Address", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address.html", null ],
      [ "com.powatag.android.sdk.AddressDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_details.html", null ],
      [ "com.powatag.android.sdk.Basket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket.html", [
        [ "com.powatag.android.sdk.PersistentBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_persistent_basket.html", null ]
      ] ],
      [ "com.powatag.android.sdk.BasketCost", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_cost.html", null ],
      [ "com.powatag.android.sdk.BasketItem", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_item.html", null ],
      [ "com.powatag.android.sdk.Campaign", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign.html", null ],
      [ "com.powatag.android.sdk.CampaignWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_workflow.html", null ],
      [ "com.powatag.android.sdk.CardNumberRange", "classcom_1_1powatag_1_1android_1_1sdk_1_1_card_number_range.html", null ],
      [ "com.powatag.android.sdk.Catalog", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog.html", null ],
      [ "com.powatag.android.sdk.CatalogWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog_workflow.html", null ],
      [ "com.powatag.android.sdk.Category", "classcom_1_1powatag_1_1android_1_1sdk_1_1_category.html", null ],
      [ "com.powatag.android.sdk.Cost", "classcom_1_1powatag_1_1android_1_1sdk_1_1_cost.html", null ],
      [ "com.powatag.android.sdk.Country", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country.html", null ],
      [ "com.powatag.android.sdk.coupon.Coupon", "classcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_coupon.html", null ],
      [ "com.powatag.android.sdk.coupon.Discount", "classcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_discount.html", null ],
      [ "com.powatag.android.sdk.CreditCardIssuer", "classcom_1_1powatag_1_1android_1_1sdk_1_1_credit_card_issuer.html", null ],
      [ "com.powatag.android.sdk.CustomDataKey", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_key.html", null ],
      [ "com.powatag.android.sdk.CustomDataValue", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_value.html", null ],
      [ "com.powatag.android.sdk.DonationInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice.html", null ],
      [ "com.powatag.android.sdk.DonationInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice_details.html", null ],
      [ "com.powatag.android.sdk.EmailSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_email_sign_in_details.html", null ],
      [ "com.powatag.android.sdk.EncryptedCvv", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv.html", null ],
      [ "com.powatag.android.sdk.FulfillmentOption", "classcom_1_1powatag_1_1android_1_1sdk_1_1_fulfillment_option.html", null ],
      [ "com.powatag.android.sdk.GeoLocation", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_location.html", null ],
      [ "com.powatag.android.sdk.GeoRestriction", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_restriction.html", null ],
      [ "com.powatag.android.sdk.Inventory", "classcom_1_1powatag_1_1android_1_1sdk_1_1_inventory.html", null ],
      [ "com.powatag.android.sdk.Invoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice.html", null ],
      [ "com.powatag.android.sdk.io.Storable", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storable.html", [
        [ "com.powatag.android.sdk.io.StorableProfileDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storable_profile_details.html", null ]
      ] ],
      [ "com.powatag.android.sdk.Merchant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant.html", null ],
      [ "com.powatag.android.sdk.MerchantLocation", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant_location.html", null ],
      [ "com.powatag.android.sdk.MobileNumberSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_mobile_number_sign_in_details.html", null ],
      [ "com.powatag.android.sdk.Payment", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment.html", null ],
      [ "com.powatag.android.sdk.PaymentDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_details.html", null ],
      [ "com.powatag.android.sdk.PaymentInstrument", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument.html", null ],
      [ "com.powatag.android.sdk.PaymentInstrumentDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details.html", null ],
      [ "com.powatag.android.sdk.PaymentInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice_details.html", null ],
      [ "com.powatag.android.sdk.PaymentMethodDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_method_details.html", null ],
      [ "com.powatag.android.sdk.PosBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket_workflow.html", null ],
      [ "com.powatag.android.sdk.Product", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product.html", null ],
      [ "com.powatag.android.sdk.ProductAttribute", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_attribute.html", null ],
      [ "com.powatag.android.sdk.ProductImage", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_image.html", null ],
      [ "com.powatag.android.sdk.ProductOption", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option.html", null ],
      [ "com.powatag.android.sdk.ProductOptionChoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_choice.html", null ],
      [ "com.powatag.android.sdk.ProductOptionState", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_state.html", null ],
      [ "com.powatag.android.sdk.ProductVariant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant.html", null ],
      [ "com.powatag.android.sdk.ProductVariantFilter", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_filter.html", null ],
      [ "com.powatag.android.sdk.ProductWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_workflow.html", null ],
      [ "com.powatag.android.sdk.Profile", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile.html", null ],
      [ "com.powatag.android.sdk.ProfileDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_details.html", null ],
      [ "com.powatag.android.sdk.ProfileIdSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_id_sign_in_details.html", null ],
      [ "com.powatag.android.sdk.ShippingPrice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_shipping_price.html", null ],
      [ "com.powatag.android.sdk.SignUpDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_sign_up_details.html", null ],
      [ "com.powatag.android.sdk.Tag", "classcom_1_1powatag_1_1android_1_1sdk_1_1_tag.html", null ],
      [ "com.powatag.android.sdk.TemporaryBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket_workflow.html", null ],
      [ "com.powatag.android.sdk.triggers.barcode.Barcode", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode.html", null ],
      [ "com.powatag.android.sdk.triggers.barcode.Image", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image.html", null ],
      [ "com.powatag.android.sdk.triggers.touch2buy.AppLink", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link.html", null ],
      [ "com.powatag.android.sdk.ui.coupon.CouponState", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1coupon_1_1_coupon_state.html", null ],
      [ "com.powatag.android.sdk.utils.ImmutableDate", "classcom_1_1powatag_1_1android_1_1sdk_1_1utils_1_1_immutable_date.html", null ],
      [ "com.powatag.android.sdk.Workflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow.html", null ],
      [ "com.powatag.android.sdk.YearMonth", "classcom_1_1powatag_1_1android_1_1sdk_1_1_year_month.html", null ]
    ] ],
    [ "ViewGroup", null, [
      [ "com.powatag.android.sdk.triggers.barcode.BarcodeTagDetectorView", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view.html", null ]
    ] ]
];