var annotated =
[
    [ "com", null, [
      [ "powatag", null, [
        [ "android", null, [
          [ "sdk", null, [
            [ "coupon", null, [
              [ "Coupon", "classcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_coupon.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_coupon" ],
              [ "CouponType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_coupon_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_coupon_type" ],
              [ "Discount", "classcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_discount.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1coupon_1_1_discount" ]
            ] ],
            [ "io", null, [
              [ "LocalStorageService", "classcom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_local_storage_service.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_local_storage_service" ],
              [ "Storable", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storable.html", null ],
              [ "StorableProfileDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storable_profile_details.html", null ],
              [ "StorageException", "classcom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storage_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storage_exception" ],
              [ "StorageService", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storage_service.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1io_1_1_storage_service" ]
            ] ],
            [ "merchant", null, [
              [ "PromotionStatus", "enumcom_1_1powatag_1_1android_1_1sdk_1_1merchant_1_1_promotion_status.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1merchant_1_1_promotion_status" ]
            ] ],
            [ "payment", null, [
              [ "BasketInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1payment_1_1_basket_invoice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1payment_1_1_basket_invoice" ]
            ] ],
            [ "product", null, [
              [ "ProductManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1product_1_1_product_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1product_1_1_product_manager" ]
            ] ],
            [ "profile", null, [
              [ "ActivationStatus", "enumcom_1_1powatag_1_1android_1_1sdk_1_1profile_1_1_activation_status.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1profile_1_1_activation_status" ],
              [ "ProfileDefaultErrorHandler", "classcom_1_1powatag_1_1android_1_1sdk_1_1profile_1_1_profile_default_error_handler.html", null ]
            ] ],
            [ "transaction", null, [
              [ "ActTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_act_transaction.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_act_transaction" ],
              [ "BasketTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_basket_transaction.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_basket_transaction" ],
              [ "DonationTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_donation_transaction.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_donation_transaction" ],
              [ "PosTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_pos_transaction.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_pos_transaction" ],
              [ "Transaction", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction" ],
              [ "TransactionManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction_manager" ],
              [ "TransactionsContainer", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transactions_container.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transactions_container" ],
              [ "TransactionType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1transaction_1_1_transaction_type" ]
            ] ],
            [ "triggers", null, [
              [ "audio", null, [
                [ "AudioTagDetector", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector" ],
                [ "AudioTagDetectorListener", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector_listener.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1audio_1_1_audio_tag_detector_listener" ]
              ] ],
              [ "barcode", null, [
                [ "Barcode", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode" ],
                [ "BarcodeFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_format.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_format" ],
                [ "BarcodeTagDetectorView", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view" ],
                [ "BarcodeTagDetectorViewListener", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view_listener.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_barcode_tag_detector_view_listener" ],
                [ "Image", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image" ],
                [ "ImageFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image_format.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1barcode_1_1_image_format" ]
              ] ],
              [ "nfc", null, [
                [ "NfcTagDetector", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1nfc_1_1_nfc_tag_detector.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1nfc_1_1_nfc_tag_detector" ]
              ] ],
              [ "touch2buy", null, [
                [ "AppLink", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link" ],
                [ "AppLinkTagDetector", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link_tag_detector.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1triggers_1_1touch2buy_1_1_app_link_tag_detector" ]
              ] ]
            ] ],
            [ "ui", null, [
              [ "coupon", null, [
                [ "CouponPicker", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1coupon_1_1_coupon_picker.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1coupon_1_1_coupon_picker" ],
                [ "CouponState", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1coupon_1_1_coupon_state.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1coupon_1_1_coupon_state" ]
              ] ],
              [ "Picker", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_picker.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_picker" ],
              [ "ProductVariantPicker", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_product_variant_picker.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_product_variant_picker" ],
              [ "Selectable", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_selectable.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1ui_1_1_selectable" ]
            ] ],
            [ "utils", null, [
              [ "ImmutableDate", "classcom_1_1powatag_1_1android_1_1sdk_1_1utils_1_1_immutable_date.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1utils_1_1_immutable_date" ],
              [ "UrlDecoder", "classcom_1_1powatag_1_1android_1_1sdk_1_1utils_1_1_url_decoder.html", null ]
            ] ],
            [ "validators", null, [
              [ "AddressDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_address_details_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_address_details_validator" ],
              [ "CardHolderNameValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_card_holder_name_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_card_holder_name_validator" ],
              [ "CardNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_card_number_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_card_number_validator" ],
              [ "CreditCardValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_credit_card_validator.html", null ],
              [ "CvvValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_cvv_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_cvv_validator" ],
              [ "DonationAmountValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_donation_amount_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_donation_amount_validator" ],
              [ "EmailValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_email_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_email_validator" ],
              [ "ExpiryDateValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_expiry_date_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_expiry_date_validator" ],
              [ "FormatValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_format_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_format_validator" ],
              [ "IssueNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_issue_number_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_issue_number_validator" ],
              [ "LuhnValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_luhn_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_luhn_validator" ],
              [ "MaxDecimalValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_decimal_value_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_decimal_value_validator" ],
              [ "MaxIntValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_int_value_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_int_value_validator" ],
              [ "MaxLengthValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_length_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_max_length_validator" ],
              [ "MinDecimalValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_decimal_value_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_decimal_value_validator" ],
              [ "MinIntValueValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_int_value_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_int_value_validator" ],
              [ "MinLengthValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_length_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_min_length_validator" ],
              [ "MobileNumberValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_mobile_number_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_mobile_number_validator" ],
              [ "ModelValidator", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_model_validator.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_model_validator" ],
              [ "NotEmptyValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_not_empty_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_not_empty_validator" ],
              [ "NotNullValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_not_null_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_not_null_validator" ],
              [ "PasscodeValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_passcode_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_passcode_validator" ],
              [ "PaymentMethodDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_payment_method_details_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_payment_method_details_validator" ],
              [ "ProfileDetailsValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_profile_details_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_profile_details_validator" ],
              [ "ProfileValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_profile_validator.html", null ],
              [ "PropertyValidator", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_property_validator.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_property_validator" ],
              [ "TitleValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_title_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_title_validator" ],
              [ "UKAddressValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_u_k_address_validator.html", null ],
              [ "ValidationError", "enumcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validation_error.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validation_error" ],
              [ "ValidationFailure", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validation_failure.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validation_failure" ],
              [ "Validator", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validator.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_validator" ],
              [ "ValidFromDateValidator", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_valid_from_date_validator.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1validators_1_1_valid_from_date_validator" ]
            ] ],
            [ "AcceptedPaymentInstrument", "classcom_1_1powatag_1_1android_1_1sdk_1_1_accepted_payment_instrument.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_accepted_payment_instrument" ],
            [ "AccessToken", "classcom_1_1powatag_1_1android_1_1sdk_1_1_access_token.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_access_token" ],
            [ "Act", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act" ],
            [ "ActDataKey", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_key.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_key" ],
            [ "ActDataKeyJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_key_json.html", null ],
            [ "ActDataType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_act_data_type" ],
            [ "ActJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_json.html", null ],
            [ "ActManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_manager" ],
            [ "ActTransaction", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction" ],
            [ "ActTransactionDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_transaction_details" ],
            [ "ActWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_act_workflow" ],
            [ "Address", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address" ],
            [ "AddressDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_address_details" ],
            [ "Base64Utils", "classcom_1_1powatag_1_1android_1_1sdk_1_1_base64_utils.html", null ],
            [ "Basket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket" ],
            [ "BasketCost", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_cost.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_cost" ],
            [ "BasketItem", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_item.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_basket_item" ],
            [ "Baskets", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets" ],
            [ "BasketsManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_baskets_manager" ],
            [ "BlockingPowaTagExecutor", "classcom_1_1powatag_1_1android_1_1sdk_1_1_blocking_powa_tag_executor.html", null ],
            [ "CallbackFactoryModule", "classcom_1_1powatag_1_1android_1_1sdk_1_1_callback_factory_module.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_callback_factory_module" ],
            [ "Campaign", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign" ],
            [ "CampaignJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_json.html", null ],
            [ "CampaignManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_manager" ],
            [ "CampaignWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_campaign_workflow" ],
            [ "CardJson", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_card_json.html", null ],
            [ "CardNumberRange", "classcom_1_1powatag_1_1android_1_1sdk_1_1_card_number_range.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_card_number_range" ],
            [ "Catalog", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog" ],
            [ "CatalogWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_catalog_workflow" ],
            [ "Category", "classcom_1_1powatag_1_1android_1_1sdk_1_1_category.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_category" ],
            [ "ContextInjector", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_context_injector.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_context_injector" ],
            [ "Cost", "classcom_1_1powatag_1_1android_1_1sdk_1_1_cost.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_cost" ],
            [ "Country", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country" ],
            [ "CountryJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country_json.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_country_json" ],
            [ "CouponManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_coupon_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_coupon_manager" ],
            [ "CreditCardIssuer", "classcom_1_1powatag_1_1android_1_1sdk_1_1_credit_card_issuer.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_credit_card_issuer" ],
            [ "CustomDataKey", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_key.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_key" ],
            [ "CustomDataKeyJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_key_json.html", null ],
            [ "CustomDataType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_type" ],
            [ "CustomDataValue", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_value.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_custom_data_value" ],
            [ "DonationInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice" ],
            [ "DonationInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_donation_invoice_details" ],
            [ "EmailSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_email_sign_in_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_email_sign_in_details" ],
            [ "EncryptedCvv", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv" ],
            [ "EncryptedCvvStorage", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv_storage.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encrypted_cvv_storage" ],
            [ "EncryptionUtils", "classcom_1_1powatag_1_1android_1_1sdk_1_1_encryption_utils.html", null ],
            [ "FulfillmentOption", "classcom_1_1powatag_1_1android_1_1sdk_1_1_fulfillment_option.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_fulfillment_option" ],
            [ "GenerateQrCodeWorkflowCallback", "classcom_1_1powatag_1_1android_1_1sdk_1_1_generate_qr_code_workflow_callback.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_generate_qr_code_workflow_callback" ],
            [ "GeoLocation", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_location.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_location" ],
            [ "GeoRestriction", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_restriction.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_restriction" ],
            [ "GeoRestrictionJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_geo_restriction_json.html", null ],
            [ "HttpRequest", "classcom_1_1powatag_1_1android_1_1sdk_1_1_http_request.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_http_request" ],
            [ "HttpResponse", "classcom_1_1powatag_1_1android_1_1sdk_1_1_http_response.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_http_response" ],
            [ "Inventory", "classcom_1_1powatag_1_1android_1_1sdk_1_1_inventory.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_inventory" ],
            [ "InventoryJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_inventory_json.html", null ],
            [ "Invoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice" ],
            [ "InvoiceBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_basket" ],
            [ "InvoiceJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_json.html", null ],
            [ "InvoiceType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_invoice_type" ],
            [ "LocalizedEntityJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_localized_entity_json.html", null ],
            [ "LoginManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_login_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_login_manager" ],
            [ "ManagerComponent", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_manager_component.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_manager_component" ],
            [ "ManagerContextModule", "classcom_1_1powatag_1_1android_1_1sdk_1_1_manager_context_module.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_manager_context_module" ],
            [ "ManagerFactory", "classcom_1_1powatag_1_1android_1_1sdk_1_1_manager_factory.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_manager_factory" ],
            [ "Merchant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant" ],
            [ "MerchantLocation", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant_location.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant_location" ],
            [ "MerchantManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_merchant_manager" ],
            [ "MobileNumberSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_mobile_number_sign_in_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_mobile_number_sign_in_details" ],
            [ "MoneyJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_money_json.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_money_json" ],
            [ "Page", "classcom_1_1powatag_1_1android_1_1sdk_1_1_page.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_page" ],
            [ "PasscodeEncryptionService", "classcom_1_1powatag_1_1android_1_1sdk_1_1_passcode_encryption_service.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_passcode_encryption_service" ],
            [ "Payment", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment" ],
            [ "PaymentCardJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_card_json.html", null ],
            [ "PaymentDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_details" ],
            [ "PaymentInstrument", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument" ],
            [ "PaymentInstrumentDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details" ],
            [ "PaymentInstrumentDetailsRequestJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details_request_json.html", null ],
            [ "PaymentInstrumentDetailsResponseJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_instrument_details_response_json.html", null ],
            [ "PaymentInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice" ],
            [ "PaymentInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice_details" ],
            [ "PaymentInvoiceJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_invoice_json.html", null ],
            [ "PaymentManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_manager" ],
            [ "PaymentMethodDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_method_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_method_details" ],
            [ "PaymentService", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_service.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_payment_service" ],
            [ "PaymentType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_payment_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_payment_type" ],
            [ "PersistentBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_persistent_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_persistent_basket" ],
            [ "PosBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket" ],
            [ "PosBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_basket_workflow" ],
            [ "PosInvoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_invoice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_invoice" ],
            [ "PosInvoiceDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_invoice_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_invoice_details" ],
            [ "PosManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_pos_manager" ],
            [ "PowaTagAuthorizationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_authorization_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_authorization_exception" ],
            [ "PowaTagCallback", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_callback.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_callback" ],
            [ "PowaTagCancellationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_cancellation_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_cancellation_exception" ],
            [ "PowaTagClient", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_client.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_client" ],
            [ "PowaTagConflictException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_conflict_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_conflict_exception" ],
            [ "PowaTagException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_exception" ],
            [ "PowaTagExecutor", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_executor.html", "interfacecom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_executor" ],
            [ "PowaTagHttpException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_http_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_http_exception" ],
            [ "PowaTagInvalidApiKeyException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_api_key_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_api_key_exception" ],
            [ "PowaTagInvalidDonationAmountException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_donation_amount_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_donation_amount_exception" ],
            [ "PowaTagInvalidTagFormatException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_tag_format_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_tag_format_exception" ],
            [ "PowaTagInvalidWorkflowTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_workflow_type_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_invalid_workflow_type_exception" ],
            [ "PowaTagKit", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_kit.html", null ],
            [ "PowaTagKitNotInitializedException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_kit_not_initialized_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_kit_not_initialized_exception" ],
            [ "PowaTagMissingRequiredActDataValuesException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_missing_required_act_data_values_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_missing_required_act_data_values_exception" ],
            [ "PowaTagNetworkException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_exception" ],
            [ "PowaTagNetworkTimeoutException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_timeout_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_network_timeout_exception" ],
            [ "PowaTagNoInternetConnectionException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_no_internet_connection_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_no_internet_connection_exception" ],
            [ "PowaTagNotFoundException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_not_found_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_not_found_exception" ],
            [ "PowaTagOutOfStockException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_out_of_stock_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_out_of_stock_exception" ],
            [ "PowaTagQrCode", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_qr_code.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_qr_code" ],
            [ "PowaTagSerializationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_serialization_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_serialization_exception" ],
            [ "PowaTagServiceException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_exception" ],
            [ "PowaTagServiceValidationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_validation_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_service_validation_exception" ],
            [ "PowaTagUndefinedPropertySerializationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_undefined_property_serialization_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_undefined_property_serialization_exception" ],
            [ "PowaTagUnsupportedActDataTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_act_data_type_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_act_data_type_exception" ],
            [ "PowaTagUnsupportedCustomDataTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_custom_data_type_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_custom_data_type_exception" ],
            [ "PowaTagUnsupportedFeatureException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_feature_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_feature_exception" ],
            [ "PowaTagUnsupportedWorkflowTypeException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_workflow_type_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_unsupported_workflow_type_exception" ],
            [ "PowaTagValidationException", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_validation_exception.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_powa_tag_validation_exception" ],
            [ "Product", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product" ],
            [ "ProductAttribute", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_attribute.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_attribute" ],
            [ "ProductCategoryJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_category_json.html", null ],
            [ "ProductCondition", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_product_condition.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_product_condition" ],
            [ "ProductImage", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_image.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_image" ],
            [ "ProductOption", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option" ],
            [ "ProductOptionChoice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_choice.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_choice" ],
            [ "ProductOptionJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_json.html", null ],
            [ "ProductOptionState", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_state.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_option_state" ],
            [ "ProductVariant", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant" ],
            [ "ProductVariantFilter", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_filter.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_filter" ],
            [ "ProductVariantJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_json.html", null ],
            [ "ProductVariantRequestJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_variant_request_json.html", null ],
            [ "ProductWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_product_workflow" ],
            [ "Profile", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile" ],
            [ "ProfileCacheManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_cache_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_cache_manager" ],
            [ "ProfileDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_details" ],
            [ "ProfileIdSignInDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_id_sign_in_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_id_sign_in_details" ],
            [ "ProfileManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_manager" ],
            [ "ProfileService", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_service.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_profile_service" ],
            [ "ServiceError", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_error.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_error" ],
            [ "ServiceErrorCodes", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_error_codes.html", null ],
            [ "ServiceModule", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_module.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_service_module" ],
            [ "ShippingPrice", "classcom_1_1powatag_1_1android_1_1sdk_1_1_shipping_price.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_shipping_price" ],
            [ "SignUpDetails", "classcom_1_1powatag_1_1android_1_1sdk_1_1_sign_up_details.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_sign_up_details" ],
            [ "Tag", "classcom_1_1powatag_1_1android_1_1sdk_1_1_tag.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_tag" ],
            [ "TagFormat", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_tag_format.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_tag_format" ],
            [ "TemporaryBasket", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket" ],
            [ "TemporaryBasketWorkflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_temporary_basket_workflow" ],
            [ "Title", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_title.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_title" ],
            [ "UnionPayCardJson", "classcom_1_1powatag_1_1android_1_1sdk_1_1_union_pay_card_json.html", null ],
            [ "WeightUnit", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_weight_unit.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_weight_unit" ],
            [ "Workflow", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow" ],
            [ "WorkflowManager", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_manager.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_manager" ],
            [ "WorkflowType", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_type.html", "enumcom_1_1powatag_1_1android_1_1sdk_1_1_workflow_type" ],
            [ "YearMonth", "classcom_1_1powatag_1_1android_1_1sdk_1_1_year_month.html", "classcom_1_1powatag_1_1android_1_1sdk_1_1_year_month" ]
          ] ]
        ] ]
      ] ]
    ] ]
];